INSERT INTO APPLICATION_USER (username, password) VALUES ('fritzel', '123456');
INSERT INTO DEPARTMENT (name) VALUES('hr');
INSERT INTO DEPARTMENT (name) VALUES('IT');
INSERT INTO DEPARTMENT (name) VALUES('KV');